import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f0f9ff",
    },
    header: {
      alignItems: 'center',
      padding: 24,
      paddingBottom: 16,
    },
    logo: {
      width: 60,
      height: 60,
      marginBottom: 12,
    },
    title: {
      fontSize: 28,
      fontWeight: "800",
      color: "#0369a1",
      marginBottom: 4,
    },
    subtitle: {
      fontSize: 16,
      color: "#64748b",
      textAlign: "center",
    },
    scrollContainer: {
      paddingHorizontal: 16,
      paddingBottom: 24,
    },
    card: {
      backgroundColor: "#fff",
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#e2e8f0",
    },
    cardTitle: {
      flex: 1,
      marginLeft: 8,
      fontSize: 16,
      fontWeight: '600',
      color: "#1e293b",
    },
    cardDate: {
      fontSize: 12,
      color: "#64748b",
    },
    dataGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    dataItem: {
      width: '48%',
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
    },
    dataValue: {
      fontSize: 16,
      fontWeight: '600',
      color: "#1e293b",
      marginLeft: 8,
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: "#ef4444",
      padding: 12,
      borderRadius: 8,
      marginTop: 8,
    },
    deleteButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
    },
    noDataContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 40,
    },
    noDataText: {
      fontSize: 18,
      color: "#64748b",
      marginTop: 16,
      textAlign: 'center',
    },
    backButton: {
      position: 'absolute',
      bottom: 24,
      right: 24,
      backgroundColor: "#64748b",
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
  });

  export default styles;